export const SET_ROOM_STATE = 'SET_ROOM_STATE'
export const SET_ROOM_UPDATING = 'SET_ROOM_UPDATING'
export const ADD_ROOM_MEMBER = 'ADD_ROOM_MEMBER'
export const REMOVE_ROOM_MEMBER = 'REMOVE_ROOM_MEMBER'
