export const ROOM_BEGIN_UPDATE = 'ROOM_BEGIN_UPDATE'
export const ROOM_FINISH_UPDATE = 'ROOM_FINISH_UPDATE'
export const ROOM_ADD_MEMBER = 'ROOM_ADD_MEMBER'
export const ROOM_REMOVE_MEMBER = 'ROOM_REMOVE_MEMBER'
