export { default as Action } from './interfaces/action'
export { default as Middleware } from './interfaces/middleware'
export { default as Reducer } from './interfaces/reducer'
export { default as Store } from './interfaces/store'
export { default as createStore } from './store'
export { default as simpleSetter } from './reducers/simple-setter'
export { default as stateDictionary } from './reducers/state-dictionary'
export { default as isFunction } from './utils/is-function'
export * from './constants/source-types'
